# CircleCI 2.1 configuration file
version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker within Executor
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build Docker image
          command: make ocrmypdf-auto
      - run:
          name: Test Docker image
          command: make test
      - store_test_results:
          path: test-results
      - run:
          name: Persist Docker image to workspace (master only)
          command: |
            mkdir -p docker-image
            touch docker-image/dummy.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker save --output docker-image/image.tar ocrmypdf-auto
            fi
      - persist_to_workspace:
          root: docker-image
          paths:
            - "*.tar"

  deploy:
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: build-output
      - run:
          name: "Load Docker image"
          command: |
            docker load --input build-output/image.tar
      - run:
          name: "Push to Docker Hub as :beta"
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
            docker tag ocrmypdf-auto cmccambridge/ocrmypdf-auto:beta
            docker push cmccambridge/ocrmypdf-auto:beta

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master
